//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Terms.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UIMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Terms.Resources.UIMessages", typeof(UIMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All details for &apos;{0}&apos; at &apos;{1}&apos;:.
        /// </summary>
        internal static string AllDetailsFor {
            get {
                return ResourceManager.GetString("AllDetailsFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An address has not been entered..
        /// </summary>
        internal static string AnAddressHasNotBeenEntered {
            get {
                return ResourceManager.GetString("AnAddressHasNotBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A name has not been entered..
        /// </summary>
        internal static string ANameHasNotBeenEntered {
            get {
                return ResourceManager.GetString("ANameHasNotBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An update has been found:.
        /// </summary>
        internal static string AnUpdateHasBeenFound {
            get {
                return ResourceManager.GetString("AnUpdateHasBeenFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A password has not been entered..
        /// </summary>
        internal static string APasswordHasNotBeenEntered {
            get {
                return ResourceManager.GetString("APasswordHasNotBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A username has not been entered..
        /// </summary>
        internal static string AUsernameHasNotBeenEntered {
            get {
                return ResourceManager.GetString("AUsernameHasNotBeenEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} possible cached credentials have been deleted..
        /// </summary>
        internal static string CachedCredentialsDeleted {
            get {
                return ResourceManager.GetString("CachedCredentialsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Find Service.
        /// </summary>
        internal static string CannotFindService {
            get {
                return ResourceManager.GetString("CannotFindService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates.
        /// </summary>
        internal static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking connection status {0} of {1}... .
        /// </summary>
        internal static string CheckingConnectionStatus {
            get {
                return ResourceManager.GetString("CheckingConnectionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking For Updates....
        /// </summary>
        internal static string CheckingForUpdates {
            get {
                return ResourceManager.GetString("CheckingForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the user credentials cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string ClearUserCredentialsConfirmation {
            get {
                return ResourceManager.GetString("ClearUserCredentialsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ].
        /// </summary>
        internal static string CloseBracket {
            get {
                return ResourceManager.GetString("CloseBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You currently have active connections open.  Are you sure you want to exit?.
        /// </summary>
        internal static string CloseMainWindowConfirmation {
            get {
                return ResourceManager.GetString("CloseMainWindowConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting details for &apos;{0}&apos; at &apos;{1}&apos;....
        /// </summary>
        internal static string CollectingDetails {
            get {
                return ResourceManager.GetString("CollectingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting physical drives for &apos;{0}&apos; at &apos;{1}&apos;....
        /// </summary>
        internal static string CollectingPhysicalDrives {
            get {
                return ResourceManager.GetString("CollectingPhysicalDrives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting processes for &apos;{0}&apos; at &apos;{1}&apos;....
        /// </summary>
        internal static string CollectingProcesses {
            get {
                return ResourceManager.GetString("CollectingProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collecting services for &apos;{0}&apos; at &apos;{1}&apos;....
        /// </summary>
        internal static string CollectingServices {
            get {
                return ResourceManager.GetString("CollectingServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This connection name already exists..
        /// </summary>
        internal static string ConnectionNameAlreadyExists {
            get {
                return ResourceManager.GetString("ConnectionNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} connections have been deleted..
        /// </summary>
        internal static string ConnectionsDeleted {
            get {
                return ResourceManager.GetString("ConnectionsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connections open.
        /// </summary>
        internal static string ConnectionsOpen {
            get {
                return ResourceManager.GetString("ConnectionsOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection statuses ({0} of {1} available):.
        /// </summary>
        internal static string ConnectionStatuses {
            get {
                return ResourceManager.GetString("ConnectionStatuses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could Not Handle Service.
        /// </summary>
        internal static string CouldNotHandleService {
            get {
                return ResourceManager.GetString("CouldNotHandleService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the connections cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteConnectionsConfirmation {
            get {
                return ResourceManager.GetString("DeleteConnectionsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting this group will also delete all the connections.  Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteGroupConfirmation {
            get {
                return ResourceManager.GetString("DeleteGroupConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the selected connections cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteSelectedConnectionsConfirmation {
            get {
                return ResourceManager.GetString("DeleteSelectedConnectionsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting the unavailable connections cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string DeleteUnavailableConnectionsConfirmation {
            get {
                return ResourceManager.GetString("DeleteUnavailableConnectionsConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_Copy.
        /// </summary>
        internal static string DuplicateNewName {
            get {
                return ResourceManager.GetString("DuplicateNewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        internal static string EditButtonText {
            get {
                return ResourceManager.GetString("EditButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Connecting To Host.
        /// </summary>
        internal static string ErrorConnectingToHost {
            get {
                return ResourceManager.GetString("ErrorConnectingToHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group name already exists..
        /// </summary>
        internal static string GroupNameAlreadyExists {
            get {
                return ResourceManager.GetString("GroupNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignored.
        /// </summary>
        internal static string Ignored {
            get {
                return ResourceManager.GetString("Ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize.
        /// </summary>
        internal static string Minimize {
            get {
                return ResourceManager.GetString("Minimize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms is still running and has been minimized to your tray..
        /// </summary>
        internal static string MinimizedToTrayWarning {
            get {
                return ResourceManager.GetString("MinimizedToTrayWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize To Tray.
        /// </summary>
        internal static string MinimizeToTray {
            get {
                return ResourceManager.GetString("MinimizeToTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clearing the groups and connections cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string NewConfirmation {
            get {
                return ResourceManager.GetString("NewConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version &apos;{0}&apos;, released on &apos;{1}&apos; is now available.  Would you like to download this update now?.
        /// </summary>
        internal static string NewUpdateAvailable {
            get {
                return ResourceManager.GetString("NewUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user credentials have been setup..
        /// </summary>
        internal static string NoCredentialsHaveBeenSetup {
            get {
                return ResourceManager.GetString("NoCredentialsHaveBeenSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No program has been specified..
        /// </summary>
        internal static string NoProgramHasBeenSpecified {
            get {
                return ResourceManager.GetString("NoProgramHasBeenSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        internal static string NoResultsFound {
            get {
                return ResourceManager.GetString("NoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates Available.
        /// </summary>
        internal static string NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [.
        /// </summary>
        internal static string OpenBracket {
            get {
                return ResourceManager.GetString("OpenBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening another connections list will clear the groups and connections, which cannot be undone.  Are you sure you want to continue?.
        /// </summary>
        internal static string OpenConfirmation {
            get {
                return ResourceManager.GetString("OpenConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an address to open/find....
        /// </summary>
        internal static string OpenConnectionPlaceholder {
            get {
                return ResourceManager.GetString("OpenConnectionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]: Address {1} is unavailable..
        /// </summary>
        internal static string PingAddressUnavailable {
            get {
                return ResourceManager.GetString("PingAddressUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging {0}....
        /// </summary>
        internal static string PingingAddress {
            get {
                return ResourceManager.GetString("PingingAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pinging &apos;{0}&apos; at {1}....
        /// </summary>
        internal static string PingingNamedAddress {
            get {
                return ResourceManager.GetString("PingingNamedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]: Status: {1}, Round Trip Time: {2}, Bytes: {3}..
        /// </summary>
        internal static string PingNoSuccess {
            get {
                return ResourceManager.GetString("PingNoSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping results for {0}:.
        /// </summary>
        internal static string PingResultsForAddress {
            get {
                return ResourceManager.GetString("PingResultsForAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping results for &apos;{0}&apos; at {1}:.
        /// </summary>
        internal static string PingResultsForNamedAddress {
            get {
                return ResourceManager.GetString("PingResultsForNamedAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}]: Address: {1}, Status: {2}, Round Trip Time: {3}, Bytes: {4}..
        /// </summary>
        internal static string PingSuccess {
            get {
                return ResourceManager.GetString("PingSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program specified does not exist..
        /// </summary>
        internal static string ProgramDoesNotExist {
            get {
                return ResourceManager.GetString("ProgramDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Res_tart.
        /// </summary>
        internal static string Restart {
            get {
                return ResourceManager.GetString("Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        internal static string Running {
            get {
                return ResourceManager.GetString("Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to perform action. Check your privileges..
        /// </summary>
        internal static string ShutdownError {
            get {
                return ResourceManager.GetString("ShutdownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning, all session data on the target machine will be lost.  Are you sure you want to continue?.
        /// </summary>
        internal static string ShutdownRestartWarning {
            get {
                return ResourceManager.GetString("ShutdownRestartWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started.
        /// </summary>
        internal static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to S_top.
        /// </summary>
        internal static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms.
        /// </summary>
        internal static string Terms {
            get {
                return ResourceManager.GetString("Terms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get details for &apos;{0}&apos; at &apos;{1}&apos;..
        /// </summary>
        internal static string UnableToGetDetails {
            get {
                return ResourceManager.GetString("UnableToGetDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        internal static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Untitled {0}.
        /// </summary>
        internal static string UntitledConnection {
            get {
                return ResourceManager.GetString("UntitledConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These user credentials already exists..
        /// </summary>
        internal static string UserCredentialNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserCredentialNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working directory does not exist..
        /// </summary>
        internal static string WorkingDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("WorkingDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
